# On the assumption that /home/edwin/sample.mp4 exists and is a valid .mp4 file, this
# command exits successfully, and the `cactus` menu disappears. To keep the menu, use the
# `alwaysShowInfo` property (as seen with  [Shift-V])
[V]
cmd = "vlc"
args = ["--loop", "--no-audio", "/home/edwin/Music/sample.mp4"]

# alwaysShowInfo is by default false, because a successfull invocation means
# you don't need the cactus pop-up window to show anymore. To still see the popup
# and related info about the service, set `alwaysShowInfo` to true
[Shift-V]
as = "exec" # default
cmd = "vlc"
args = ["--loop", "--no-audio", "/home/edwin/Music/sample.mp4"]
alwaysShowInfo = true

# You also have access to environment variables via Go templates for the `cmd` and
# `args` properties
[Ctrl-V]
cmd = "vlc"
args = ["--loop", "--no-audio", "{{ .HOME }}/Music/sample.mp4"]
alwaysShowInfo = true

[M]
# try as = sh
as = "exec"
cmd = "vlc --loop --ignore-filetypes"
wait = true

[J]
cmd = "brave"
