# Each hotkey is a property with members defining the hotkey's behaviors
# After pressing [V], the command exits successfully (if the file exists)
# and the `cactus` menu disappears. To keep the menu, use the
# `alwaysShowInfo` property (as seen with  [Shift-V])
[V]
cmd = "vlc"
args = ["--loop", "--no-audio", "/home/edwin/Music/sample.mp4"]

# alwaysShowInfo is by default false, because a successfull invocation means
# you don't need the cactus pop-up window to show anymore. To still see the popup
# and related info about the service, set `alwaysShowInfo` to true.
# And, when using modifiers like 'Shift', ensure you press it first, _then_
# the alphabetical key
[Shift-V]
as = "exec" # default
cmd = "vlc"
args = ["--loop", "--no-audio", "/home/edwin/Music/sample.mp4"]
alwaysShowInfo = true

# You also have access to environment variables `cmd` and `args` properties
# It's implemented using sprig, so you can use a whole
# host of [functions](https://masterminds.github.io/sprig)
[Ctrl-V]
cmd = "vlc"
args = ["--loop", "--no-audio", '{{ env "HOME" }}/Music/sample.mp4']
alwaysShowInfo = true

# If you choose to execute with the shell, you do not need `args`. Valid values
# for `as` are "sh" and "bash"
[S]
as = "sh"
cmd = 'vlc --loop --no-audio "$HOME/Music/sample.mp4" >/dev/null </dev/null'
alwaysShowInfo = true
